#!/bin/bash
x=$(curl -u "$1" --silent "https://mail.google.com/mail/feed/atom" |  grep -oPm1 "(?<=<name>)[^<]+" | sed '1d')
y=$(curl -u "$1" --silent "https://mail.google.com/mail/feed/atom" |  grep -oPm1 "(?<=<summary>)[^<]+" | sed '1d')
if [ ! -z "$x" ] && [ ! -z "$y" ]; then
declare -i counter=1
while [ $counter != $(wc -l <<<$x) ]; do
	sed -n ''$counter'p' <<<$x >> Your_Mail
	sed -n ''$counter'p' <<<$y >> Your_Mail
	echo "" >> Your_Mail
	counter+=1
done
fi
